### ISSUE TITLE
DummyCore/EssentialCraft 3/Essential Thaumaturgy/Difficult Life

### ISSUE THREAD

**Issue by Anarcraft** [Anarcraft/FTBOP#11]
A. Modpack permissions: Good to go, would need to add link to secondary sheet.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2286105-dt-mods-essentialcraft-3-essential-thaumaturgy

**Comment by superzip** [comment]
added to secondary sheet

**Comment by Anarcraft** [comment]
Mods added successfully.
