### ISSUE TITLE
Witching Gadgets

### ISSUE THREAD

**Issue by Anarcraft** [Anarcraft/FTBOP#13]
A. Modpack permissions: Good to go, would need to add link to secondary sheet.

http://www.curse.com/mc-mods/minecraft/228268-witching-gadgets

**Comment by superzip** [comment]
added to secondary sheet

**Comment by Anarcraft** [comment]
Actually not going to install this for now reading a comment about "world not loading" and then another comment confirming it.  Will keep an eye on it, removing from sheet.
