### ISSUE TITLE
ProjectE Changes

### ISSUE THREAD

**Issue by Anarcraft** [Anarcraft/FTBOP#14]
A. Disable Energy Condensors.
B. Disable Transmutation Table.  Verify tablet is also unavailable.
C. Disable Tome.
D. Disable EMC tooltips.

**Comment by joopez1** [comment]
thank god. wait wat is left?

**Comment by Anarcraft** [comment]
All of the items and armor the mod adds, a lot of things!

**Comment by Anarcraft** [comment]
Done, test.

**Comment by Anarcraft** [comment]
Good.
