### ISSUE TITLE
RFTools

### ISSUE THREAD

**Issue by Anarcraft** [Anarcraft/FTBOP#20]
A. Modpack permissions: Good to go, would need to add link to secondary sheet.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2229562-rftools-dimension-builder-teleportation-crafter

**Comment by superzip** [comment]
added to secondary sheet

optional leave a post that we are using his mod in our pack ether as a PM or in the forumtread

**Comment by Anarcraft** [comment]
Once this is on Technic I'll create a forum post in the thread then close this.

**Comment by Anarcraft** [comment]
Posted.
