### ISSUE TITLE
Forge Essentials (Client & Server)

### ISSUE THREAD

**Issue by superzip** [Anarcraft/FTBOP#30]
curse site
http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735

wiki for setup
https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki
https://github.com/ForgeEssentials/ForgeEssentialsMain

license is "Eclipse Public License - v 1.0" , so a link is fine (i think)

**Comment by Anarcraft** [comment]
Confirmed permissions in IRC, added to secondary data.
