### ISSUE TITLE
Dropped items botania open crate

### ISSUE THREAD

**Issue by etb845** [Anarcraft/FTBOP#4]
Open Crate from Botania will keep dropping items even if it isnt properly load and it keeps items from disappearing. This doesnt seem like an error just not used in the right build.

**Comment by Anarcraft** [comment]
What do you mean by "isn't properly load"?  Loaded?  Not in a loaded chunk or something else?

**Comment by etb845** [comment]
I mean the hungry node isnt loaded which the open crate is dropping items into so the items just stack sorry didnt get back on this till now.

**Comment by Anarcraft** [comment]
Oh so it was just a chunk loading issue? (crate wasn't in the same chunk as the node)

**Comment by etb845** [comment]
no it was a couple blocks above it

**Comment by Anarcraft** [comment]
Still a little confused but since you said "This doesnt seem like an error just not used in the right build." I'm just gonna close this.
