### ISSUE TITLE
Dynmap

### ISSUE THREAD

**Issue by Anarcraft** [Anarcraft/FTBOP#5]
A. Server only.
B. Modpack permissions: I don't see this, investigate.
C. Would want to include link to Dynmap in server info.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft

**Comment by superzip** [comment]
B. server only mod, no permission needed, since no distribution will happen.

**Comment by Anarcraft** [comment]
B. A server pack will be available for download as well if others want to set up a server.

**Comment by Anarcraft** [comment]
Trying to understand "Apache License version 2.0" just seems like modern day ptolemaic system (over complicated to the point of non-sense).  This mod is not going to be distributed.  I'll add it to the UgL server though.
