### ISSUE TITLE
pvpToggle

### ISSUE THREAD

**Issue by Anarcraft** [Anarcraft/FTBOP#8]
A. Modpack permissions: Good to go, would need to add link to secondary sheet.

http://www.curse.com/mc-mods/minecraft/223394-pvptoggle

**Comment by joopez1** [comment]
no. pvp is good

**Comment by Anarcraft** [comment]
Yes, we will still have PVP, this should allow us to have more control over where PVP actually works.

**Comment by Anarcraft** [comment]
Test and configure on the server then close this.

**Comment by Anarcraft** [comment]
The mod has issues.  It says forever I'm in cooldown now when I do /pvp off.

**Comment by Anarcraft** [comment]
Working after I enabled PVP on the server.
