### ISSUE TITLE
Realistic World Gen

### ISSUE THREAD

**Issue by Anarcraft** [Anarcraft/FTBOP#9]
A. Modpack permissions: Good to go, would need to add link to secondary sheet.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1281910-teds-world-gen-mods-realistic-world-gen-alpha-1-3

**Comment by superzip** [comment]
added to secondary sheet

**Comment by Anarcraft** [comment]
Added ATG instead, already on primary sheet.
